name: Publish Python 🐍 distributions 📦 to PyPI
# name: Bump Version and Create PR

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: true
        default: patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump the version
        id: bump_version
        run: |
          echo "Current version: $(cat VERSION)"
          bump2version patch --allow-dirty --current-version $(cat VERSION) VERSION
          echo "New version: $(cat VERSION)"
          echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Commit version bump
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ env.version }}"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI (Optional)
        if: ${{ github.ref_name == 'master' }}
        uses: pypa/gh-action-pypi-publish@v1
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


  build-and-publish-test-pypi:
    needs: bump-version
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install setuptools wheel twine
      - name: Build and publish to TestPyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

  build-and-publish-pypi:
    needs: build-and-publish-test-pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install setuptools wheel twine
      - name: Build and publish to PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
