name: Publish Python 🐍 distributions 📦 to PyPI
# name: Bump Version and Create PR

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, major)'
        required: true
        default: patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install bump2version
        run: pip install bump2version

      - name: Read and bump version
        id: bump_version
        run: |
          echo "Current version: $(cat VERSION)"
          bump2version ${{ github.event.inputs.release_type }} --allow-dirty --current-version $(cat VERSION) VERSION
          echo "New version: $(cat VERSION)"
          echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Create and push branch
        run: |
          git fetch origin main:main
          git checkout main
          BRANCH_NAME="bump-version-${{ env.version }}"
          git checkout -b $BRANCH_NAME
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version to ${{ env.version }}"
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "bump-version-${{ env.version }}"
          base: "main"  # Ensure 'base' is the default branch
          title: "Bump version to ${{ env.version }}"
          body: |
            ## Version update
            This pull request bumps the project version to `${{ env.version }}`. Please review and merge.


  build-and-publish-test-pypi:
    needs: bump-version
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install setuptools wheel twine
      - name: Build and publish to TestPyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

  build-and-publish-pypi:
    needs: build-and-publish-test-pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install setuptools wheel twine
      - name: Build and publish to PyPI
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
